### ISSUE TITLE
Stop flickering when page is manipulated

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#2689]
Probably the problem lies within my setup.

I get strong flickering when switching between sections in the top navigation bar by using the pointer. but little to no flickering when using Vimium on _Chromium Version 52.0.2743.116 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)_

Little flickering when switching between sections in the top navigation bar by using the pointer on _Ubuntu Web Browser_

Perhaps, one of these sources can provide a solution:
https://www.paulirish.com/2009/avoiding-the-fouc-v3/
http://james.padolsey.com/snippets/avoiding-dom-flickering/

**Comment by jacogr** [comment]
We should just confirm that the same happens with the final built as served by 127.0.0.1:8180 - it could be related to the dev environment only.

**Comment by ngotchac** [comment]
Isn't this fixed now ?

**Comment by 5chdn** [comment]
@bjornwgnr does this still happen?

**Comment by bjornwgnr** [comment]
Chromium Version 56.0.2924.76: I still get flickering when switching between sections in the top navigation bar by using the pointer, but not when switching by using Vimium.

No problems with _Ubuntu Web Browser_ anymore.

_Running Ubuntu 16.04 (64-bit)_

**Comment by 5chdn** [comment]
This issue is labelled with _bug_: The client fails to follow expected behavior; and is inactive for several months. It's neither assigned nor linked to a milestone.

Please, decide on a deadline and assign this ticket to a developer within 7 days or close it if fixed otherwise.

**Comment by keorn** [comment]
Reopen if happens on new UI
