### ISSUE TITLE
Default configuration file no longer current (?) [Arch Linux Parity 1.6.6]

### ISSUE THREAD

**Issue by lkblkb** [paritytech/parity#5729]
Using the default configuration file listed at the link below causes Parity to open with errors and eventually fail on Linux (Arch). Perhaps the defaults within Parity have changed? 

https://github.com/paritytech/parity/wiki/Configuring-Parity

Error examples:

     You might have supplied invalid parameters in config file.
    expected a value of type `array`, but found a value of type `string` for the key 
    `account.password`
&nbsp;

    You have some extra fields in your config file:

    [dapps]
    password = "test_pass"

    [network]
    disable = false
    serve_light = true

    [parity]
    light = false
&nbsp;

    Error opening reserved nodes file: No such file or directory (os error 2)

**Comment by 5chdn** [comment]
Thanks for reporting, will look into this asap.

**Comment by 5chdn** [comment]
Done.

**Comment by adyshimony** [comment]
Still getting errors for the default file taken from here
https://wiki.parity.io/Configuring-Parity#config-file

"Error opening reserved nodes file"

**Comment by Tbaut** [comment]
@adyshimony if you have a look at the config file:
> reserved_peers = "./path_to_file"

You need to adapt this to your environment and OS.
Feel may find the [config generator](https://paritytech.github.io/parity-config-generator/) more handy to create your config file.
