### ISSUE TITLE
Empty <div> appears during transaction execution

### ISSUE THREAD

**Issue by codewiz** [paritytech/parity#5751]
An empty rectangle appears after selecting "Send" on a plain transaction. The rectangle covers the bottom of the page and disables interaction with the rest of the UI:

![image](https://cloud.githubusercontent.com/assets/1184492/26728240/8e3dcfd0-4777-11e7-9719-1560f418b014.png)

I can consistently reproduce by making a 1 ETH transfer from one of my addresses to another. As soon as I hit "Send", the rectangle appears and the only way to get rid of it is killing parity.

I'm building Parity from head of master, and this bug appeared several days ago.

**Comment by tomusdrw** [comment]
This has been fixed in latest master recently. Please update. #5698

**Comment by codewiz** [comment]
I am building from head, but the bug is still present. Could it be that that the parity-ui-precompiled needs to be updated?

**Comment by tomusdrw** [comment]
Can't reproduce it. Can you tell us what errors you see in the console?

**Comment by codewiz** [comment]
It's been fixed recently

On June 7, 2017 6:01:56 AM EDT, "Tomasz Drwięga" <notifications@github.com> wrote:
>Can't reproduce it. Can you tell us what errors you see in the console?

-- 
ベルニー
Sent from my Android device with K-9 Mail.

**Comment by codewiz** [comment]
It's been fixed recently.
