### ISSUE TITLE
Parity Chrome Integration extension not detecting node from v1.10

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity#8426]
> I'm running:
>
> - **Which Parity version?**: 1.10.0
> - **Which operating system?**: any
> - **How installed?**: any
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: any

The Chrome extension doesn't detect the local running node out of the box with Parity v1.10 and higher. Users need to launch Parity with the flag `--force-ui` for it to work as expected.

**Comment by folsen** [comment]
@tomusdrw I can't remember if we fixed this yet or if it's still in waiting to be picked?

**Comment by tomusdrw** [comment]
Not fixed yet, UI is required for the extension for now, so waiting to be picked.

**Comment by gnunicorn** [comment]
So, if the default behaviour is that the UI isn't started and we need the user to run it with `--force-ui`, what is the expected fix? Showing that error in the UI/Chrome extention to give the user some context what to do?

**Comment by tomusdrw** [comment]
@gnunicorn The extension shouldn't really require the UI for anything. Currently (afair) the extension is using :8180 for:
1. To extract authentication token
2. To query the RPC and figure out what the WS address is.
3. To check if the node is running by executing `/ping`

To address the issue we need to address all 3:
1. This should be a popup dialog asking for manual token input
2,3. We can use `:8545` for this instead.

**Comment by 5chdn** [comment]
This is an extension issue, isn't it? We are not providing anything on :8180 anymore, so not much we can do on client side, right?

**Comment by Tbaut** [comment]
Closing in favor of https://github.com/paritytech/parity-extension/issues/123

**Comment by 5chdn** [comment]
:p
